plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.minecraftforge.gradle' version '[6.0,6.2)'
}

version = '1.0.9'
group = 'com.oritong.oritongsdiamondcore'
archivesBaseName = 'oritongsdiamondcore'

java.toolchain.languageVersion = JavaLanguageVersion.of(17)

minecraft {
    mappings channel: 'official', version: '1.20.1'

    runs {
        client {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                oritongsdiamondcore { source sourceSets.main }
            }
        }
        server {
            workingDirectory project.file('run')
            property 'forge.logging.markers', 'REGISTRIES'
            property 'forge.logging.console.level', 'debug'
            mods {
                oritongsdiamondcore { source sourceSets.main }
            }
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { url = 'https://maven.minecraftforge.net/' }
    flatDir { dir 'libs' }
}

dependencies {
    minecraft 'net.minecraftforge:forge:1.20.1-47.2.0'
    compileOnly files('libs/ae2-7148487.jar')
    compileOnly files('libs/jei-1.20.1-forge-15.20.0.106.jar')
    compileOnly files('libs/emi-1.1.24+1.20.1+forge.jar')
    compileOnly files('libs/industrialforegoing-1.20.1-3.5.21.jar')
    compileOnly files('libs/bettergtae-1.2.2.jar')
    compileOnly files('libs/Botania-1.20.1-448-FORGE.jar')
    compileOnly files('libs/TConstruct-1.20.1-3.11.2.166.jar')
    compileOnly files('libs/Mantle-1.20.1-1.11.104.jar')
    compileOnly files('libs/merequester-forge-1.20.1-1.2.1.jar')
    compileOnly files('libs/pipez-forge-1.20.1-1.2.21.jar')
    compileOnly files('../pattern_encoding_terminal_quick_math 1.20.1/local_maven/com/glodblock/github/expatternprovider/1.4.12/expatternprovider-1.4.12.jar')
    compileOnly files('../pattern_encoding_terminal_quick_math 1.20.1/local_maven/com/gregtechceu/gtceu/7.5.3/gtceu-7.5.3.jar')
    compileOnly files('../pattern_encoding_terminal_quick_math 1.20.1/local_maven/com/lowdragmc/ldlib/1.0.50/ldlib-forge-1.0.50.jar')
}

jar {
    manifest {
        attributes([
            "Specification-Title"     : "oritongsdiamondcore",
            "Specification-Vendor"    : "oritong",
            "Specification-Version"   : "1",
            "Implementation-Title"    : project.name,
            "Implementation-Version"  : project.jar.archiveVersion,
            "Implementation-Vendor"   : "oritong",
            "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ"),
            "MixinConfigs"            : "oritongsdiamondcore.mixins.json"
        ])
    }
}

jar.finalizedBy('reobfJar')

publishing {
    publications {
        register('mavenJava', MavenPublication) { artifact jar }
    }
    repositories {
        maven { url "file://${project.projectDir}/mcmodsrepo" }
    }
}
